language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    - npm install gulp

script:
    - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
	rm -rf public
	mkdir public
	git worktree prune
	rm -rf .git/worktrees/public/
	rm -rf public/*
	gulp build
	cd public
	git add -f --ignore-errors --all
    git -c user.name='blafond' -c user.email='blafond' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
