baseURL: "https://teiid.io/"
languageCode: "en-gb"
title: "Teiid"
theme: "dracoio"
relativeURLs: true
googleAnalytics: "UA-98663114-1"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github
    
params:
  proddtm: "https://www.redhat.com/dtm.js"
  stagingdtm: "https://www.redhat.com/dtm-staging.js"
